### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by rvehall** [Women-Who-Code-Phoenix/lah#12]
As a user, I would like to be able to navigate to Home, the About page, and to this repo.

AC-
- [x] Use footer from [Vuetify](https://vuetifyjs.com/en/components/footer/#company-footer)
- [x] The primary color needs to match that of the header (hex #1976D2)
- [x] Needs to have the year the Life At Home
- [x] Needs to have links to the home page, the About page, and to this repo.
- [x] Needs to Sticky to the bottom

- Design: https://preview.uxpin.com/fa165a3181b8d0c14e4cf54137715fa4f59e76d8#/pages/127018043/simulate/no-panels?mode=i

**Comment by chrissyalbert** [comment]
Hi Violet, I made the pull request and it's going straight to your original repo. I'm not sure if that is a mistake on my part (since I thought I was making the pull request to the WWC Phoenix repo. I'm new to this and not fluent with all the procedures for pushing and pulling branches.

**Comment by rvehall** [comment]
Hi, @chrissyalbert, I see your PR. If you don't set it when you originally create the PR (image 1), at the top of your PR, click Edit and you can change where you're wanting to merge into (image 2). I see you set it to the WWC `master` branch. It should be into `development`. Thanks!

<img width="1022" alt="Screen Shot 2020-04-21 at 7 45 10 AM" src="https://user-images.githubusercontent.com/2738022/79879816-0b8ebb00-83a4-11ea-9a8b-06556eb9af7d.png">

<img width="1051" alt="Screen Shot 2020-04-21 at 7 43 09 AM" src="https://user-images.githubusercontent.com/2738022/79879631-cbc7d380-83a3-11ea-87ab-e165a0f5bb1a.png">

**Comment by chrissyalbert** [comment]
Closing issue.

**Comment by rvehall** [comment]
This has not been pushed into development yet. Reopening.
